version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
    open-pull-requests-limit: 20

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"

  - package-ecosystem: "npm"
    directory: "/scripts/release"
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      time: "01:00"
