name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Node.js
        uses: actions/setup-node@v3.7.0
        with:
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Build Package
        run: yarn build --clean

      - name: Upload Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: dist
          path: dist
          if-no-files-found: error
