name: Check Sizes

on:
  pull_request:

jobs:
  check-sizes:
    name: Check Sizes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: "yarn"

      # This step calls `git reset`
      # It should be the last step
      - name: Check Sizes
        uses: preactjs/compressed-size-action@2.5.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          pattern: "./dist/**/*"
          compression: none
